service: AWS-STARTWARS
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  iamRoleStatements:
      - Effect: Allow
        Action: 
          - dynamodb:* 
        Resource:
          - arn:aws:dynamodb:us-west-2:770955909977:table/GeneralTable

functions:
  createPlanetsTable:
      handler: src/generalTable/createPlanet.createPlanet
      events:
        - httpApi:
            path: /planets
            method: post
  getPlanetsTable:
      handler: src/generalTable/getPlanets.getPlanets
      events:
        - httpApi:
            path: /planets
            method: get
  updatePlanetsTable:
    handler: src/generalTable/updatePlanet.updatePlanet
    events:
      - httpApi:
          path: /planets/{id}
          method: put
  getPlanetTable:
      handler: src/generalTable/getPlanet.getPlanet
      events:
        - httpApi:
            path: /planets/{id}
            method: get                                         
resources:
  Resources:        
      GeneralTable: 
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: GeneralTable
          BillingMode: PAY_PER_REQUEST
          AttributeDefinitions:
            - AttributeName: pk
              AttributeType: S
            - AttributeName: sk
              AttributeType: S   
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: sk
              KeyType: RANGE                 